routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CarController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('cars', CarController::class);

app/Models/Cars.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cars extends Model
{
    use HasFactory;

    protected $fillable = ['registration', 'brand', 'model', 'engine'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cars;


class CarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $car = Cars::all();
        return view('index', compact('car'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $carData = $request->validate([
            'registration' => 'required|max:20',
            'brand' => 'required|max:50',
            'model' => 'required|max:50',
            'engine' => 'required|max:20'
        ]);

        $car = Cars::create($carData);

        return redirect('/cars')->with('completed', 'Car has been saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**f
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $car = Cars::findOrFail($id);

        return view('edit', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateData = $request->validate([
            'registration' => 'required|max:20',
            'brand' => 'required|max:50',
            'model' => 'required|max:50',
            'engine' => 'required|max:20'
        ]);

        Cars::whereId($id)->update($updateData);

        return redirect('/cars')->with('completed', 'Car has been updated');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $car = Cars::findOrFail($id);
        $car->delete();

        return redirect('/cars')->with('completed', 'Car has been deleted');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/create.blade.php
@extends('layout')

@section('content')

    <style>
        .container {
            max-width: 450px;
        }
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="card push-top">
        <div class="card-header">
            Add Car
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('cars.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="registration">Registration</label>
                    <input type="text" class="form-control" name="registration"/>
                </div>
                <div class="form-group">
                    <label for="brand">Brand</label>
                    <input type="text" class="form-control" name="brand"/>
                </div>
                <div class="form-group">
                    <label for="model">Model</label>
                    <input type="text" class="form-control" name="model"/>
                </div>
                <div class="form-group">
                    <label for="engine">Engine</label>
                    <input type="text" class="form-control" name="engine"/>
                </div>
                <button type="submit" class="btn btn-block btn-danger">Create Car</button>
            </form>
        </div>
    </div>
@endsection

resources/views/edit.blade.php
@extends('layout')

@section('content')

    <style>
        .container {
            max-width: 450px;
        }
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="card push-top">
        <div class="card-header">
            Edit & Update
        </div>
        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div><br />
            @endif
            <form method="post" action="{{ route('cars.update', $car->id) }}">
                <div class="form-group">
                    @csrf
                    @method('PATCH')
                    <label for="registration">Registration</label>
                    <input type="text" class="form-control" name="registration" value="{{ $car->registration }}"/>
                </div>
                <div class="form-group">
                    <label for="brand">Brand</label>
                    <input type="text" class="form-control" name="brand" value="{{ $car->brand }}"/>
                </div>
                <div class="form-group">
                    <label for="model">Model</label>
                    <input type="text" class="form-control" name="model" value="{{ $car->model }}"/>
                </div>
                <div class="form-group">
                    <label for="engine">Engine</label>
                    <input type="text" class="form-control" name="engine" value="{{ $car->engine }}"/>
                </div>
                <button type="submit" class="btn btn-block btn-danger">Update Car</button>
            </form>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('content')

    <style>
        .push-top {
            margin-top: 50px;
        }
    </style>

    <div class="card-header">
        Cars list
    </div>
    <div class="push-top">
        <table class="table">
            <thead>
            <tr class="table-warning">
                <td>ID</td>
                <td>Registration</td>
                <td>Brand</td>
                <td>Model</td>
                <td>Engine</td>
                <td class="text-center">Action</td>
            </tr>
            </thead>
            <tbody>
            @foreach($car as $cars)
                <tr>
                    <td>{{$cars->id}}</td>
                    <td>{{$cars->registration}}</td>
                    <td>{{$cars->brand}}</td>
                    <td>{{$cars->model}}</td>
                    <td>{{$cars->engine}}</td>
                    <td class="text-center">
                        <a href="{{ route('cars.edit', $cars->id)}}" class="btn btn-primary btn-sm">Edit</a>
                        <form action="{{ route('cars.destroy', $cars->id)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>OK Cars Test</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" type="text/js"></script>
    </body>
</html>